### ISSUE TITLE
Bot as a background painter

### ISSUE THREAD

**Issue by jandetlefsen** [RomiRand/PoapArtBot#1]
Hey i've tried your bot the other day and pretty dope. 
There is of course the issue that it's kind of cheating so when possible ppl will find it more original and preferablel to paint by hand.

But what if you could have an option that the bot never changes pixel that have already been set to a color before? That way you could have the bot paint along without disturbing anyone. In reality the bot would just pain background images on space where no other painter has any intention to create anything. The bot would become a legit contributor alongside of humans, without disturbing them, like a cobot. That could be a legit use of the bot in real painting campaigns.

**Comment by RomiRand** [comment]
Great idea! I'll add another weird-looking button for this option somewhere.
